/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Modelo.Empleado;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;


public class TablaPrincipal extends javax.swing.JFrame {

    DefaultTableModel modelo = new DefaultTableModel();
    Empleado empleado;

    public TablaPrincipal() {
        initComponents();
    }

    public JTable getTablaTrabajadores() {
        return tablaTrabajadores;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaTrabajadores = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnAgregar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        presupuesto = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        duracion = new javax.swing.JTextField();
        FONDO = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaTrabajadores.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tablaTrabajadores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nombre", "Apellido", "Rut", "Telefono", "Rol", "Salario", "Estado"
            }
        ));
        jScrollPane2.setViewportView(tablaTrabajadores);
        tablaTrabajadores.getAccessibleContext().setAccessibleName("");
        tablaTrabajadores.getAccessibleContext().setAccessibleDescription("");

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(21, 46, 581, 323));

        jLabel1.setFont(new java.awt.Font("MV Boli", 1, 26)); // NOI18N
        jLabel1.setText("Nomina trabajadores para la obra ");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 0, -1, -1));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnAgregar.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        btnAgregar.setText("Agregar");
        jPanel2.add(btnAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 47, 100, 35));

        btnEliminar.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 187, 100, 35));

        btnSalir.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        btnSalir.setText("Salir");
        jPanel2.add(btnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 312, 100, 35));

        btnActualizar.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        btnActualizar.setText("Actualizar");
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 120, 120, 35));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 10, 120, 358));

        presupuesto.setBackground(new java.awt.Color(0, 255, 255));
        presupuesto.setFont(new java.awt.Font("Yu Gothic UI Semibold", 1, 14)); // NOI18N
        jPanel1.add(presupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 490, 480, 30));

        jButton1.setFont(new java.awt.Font("MV Boli", 1, 14)); // NOI18N
        jButton1.setText("Generar Presupuesto");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 440, 230, 30));

        jLabel2.setFont(new java.awt.Font("MV Boli", 0, 14)); // NOI18N
        jLabel2.setText("Duracion (dias) :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 120, 40));

        duracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                duracionActionPerformed(evt);
            }
        });
        jPanel1.add(duracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, 110, 30));

        FONDO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Img/tablaaa.jpg"))); // NOI18N
        jPanel1.add(FONDO, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        modelo = (DefaultTableModel) tablaTrabajadores.getModel();
        String nom = (String) modelo.getValueAt(tablaTrabajadores.getSelectedRow(), 0);
        int filaSeleccionada = tablaTrabajadores.getSelectedRow(); //se pincha la fila del trabajador a eliminar
        int respuesta = JOptionPane.showConfirmDialog(this, "Desea borrar a: " + nom + "?", "Confirmar", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (respuesta == JOptionPane.YES_OPTION) {
            modelo.removeRow(filaSeleccionada);
        } else {
            System.out.println("no acepto");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        modelo = (DefaultTableModel) tablaTrabajadores.getModel();
        String nombre = (String) modelo.getValueAt(tablaTrabajadores.getSelectedRow(), 0);
        String apellido = (String) modelo.getValueAt(tablaTrabajadores.getSelectedRow(), 1);
        String rut = (String) modelo.getValueAt(tablaTrabajadores.getSelectedRow(), 2);
        int telefono = Integer.parseInt(String.valueOf(modelo.getValueAt(tablaTrabajadores.getSelectedRow(), 3)));
        String rol = (String) modelo.getValueAt(tablaTrabajadores.getSelectedRow(), 4);
        int salario = Integer.parseInt(String.valueOf( modelo.getValueAt(tablaTrabajadores.getSelectedRow(), 5)));
        String estado = (String) modelo.getValueAt(tablaTrabajadores.getSelectedRow(), 6);
        int filaSeleccionada = tablaTrabajadores.getSelectedRow();
        //se actulizan los datos de cada trabajador
        empleado = new Empleado(nombre, apellido, rut, telefono, rol, salario, estado);
        Actualizar actualizar = new Actualizar(empleado, filaSeleccionada, this.getTablaTrabajadores());
        actualizar.setLocationRelativeTo(null);
        actualizar.setVisible(true);
        //this.setVisible(false);
        
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void duracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_duracionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_duracionActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        modelo = (DefaultTableModel) tablaTrabajadores.getModel();
        
        int filas = modelo.getRowCount();
        int presupuesto =0;
        int contador=0;
        for (int i = 0; i < filas; i++) {
            String estado = (String) modelo.getValueAt(i, 6);
            if (estado.equals("Activo")) {
                int salario = Integer.parseInt(String.valueOf(modelo.getValueAt(i, 5)));
                presupuesto+=salario;
                contador+=1;
            }
        }
        int duracion = Integer.parseInt(this.duracion.getText());
        this.presupuesto.setText("Para realizar la obra con "+contador+" trabajadores en "+duracion+" dias PPTotal = $ "+String.valueOf(presupuesto*duracion));
        //se calcula el costo total de la obra
    }//GEN-LAST:event_jButton1ActionPerformed


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TablaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TablaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TablaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TablaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TablaPrincipal().setVisible(true);//se muestra la tabla
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel FONDO;
    public javax.swing.JButton btnActualizar;
    public javax.swing.JButton btnAgregar;
    public javax.swing.JButton btnEliminar;
    public javax.swing.JButton btnSalir;
    private javax.swing.JTextField duracion;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel presupuesto;
    public javax.swing.JTable tablaTrabajadores;
    // End of variables declaration//GEN-END:variables
    
}
